language: node_js
node_js:
  - '12'

script:
  - npm run deploy

deploy:
  provider: surge
  project: ./dist/
  domain: react-typescript-styled-system-boilerplate.surge.sh
  skip_cleanup: true
  on:
    branch: master