language: node_js
node_js:
  - '12'

cache:
  directories:
    - node_modules

before_deploy:
  - npm install netlify-cli -g
  - npm run deploy

deploy:
  provider: surge
  project: ./dist/
  domain: react-typescript-styled-system-boilerplate.surge.sh
  on:
    branch: master